# Homework 1: Sports and Statistics

### Step 1: 

Download [R](https://cran.r-project.org/) and [RStudio](https://www.rstudio.com/products/RStudio/#Desktop). Next, print and refer to this 
[RMarkdown cheatsheet](http://shiny.rstudio.com/articles/rm-cheatsheet.html). 

### Step 2: 

Create a new Markdown file by going to -- `File` -- `New file` -- `RMarkdown` and selecting `HTML`.

### Step 3: 

Save the file as `Homework 0,` and make sure to enter your name where it says `Author.`

### Step 4: 

Answer the following questions. At the end of your assignment, click `Knit HTML` at the top of RStudio, and print the resulting document. *Note*: I do not want a printed homework assignment with your handwriting on it!!!


### Q1: What math or stats classes have you taken while at college?  What experience do you have using R or RStudio?

Answer here:


### Q2: What sports do you or have you participated in, and what ones do you watch frequently?

Answer here:


There are some excellent Markdown resources. In addition to the 
[RMarkdown cheatsheet](http://shiny.rstudio.com/articles/rm-cheatsheet.html), check out the work of Professor [Jenny Bryan](https://stat545-ubc.github.io/index.html), which includes [tips for first-time R users](https://stat545-ubc.github.io/block002_hello-r-workspace-wd-project.html), [basic data manipulation steps](https://stat545-ubc.github.io/block006_care-feeding-data.html), and [different R objects](https://stat545-ubc.github.io/block004_basic-r-objects.html)

### Q3: Using the information above, write five things about the R software that you did not know beforehand. 

Answer here:


Now that you are done with your first assignment, be sure to `Knit HTML`!


