## Sports Data

There are a wide variety of public data sets or R packages available for anyone looking to do statistics and sports research. This working list is designed to provide teachers, professionals, and students one guide to what's out there. I'll be adding items throughout my semester of teaching [Sports and Stats](statsbylopez.com/stats-sports-class/), so feel free to check back. Also, this list is meant to provide raw data, either cleaned or uncleaned, and so I won't be linking to site's that have focused more on the analysis piece. Sites with an **Rstats** label are tutorials or packages designed fort the [R](cran.r-project.org) statistical software. 


### All sports

I usually recommend the sports-reference sites ([find several here](http://www.sports-reference.com/)) for any aggregated team or individual level data. A great starting point. 


### Baseball

- The [Lahman](https://cran.r-project.org/web/packages/Lahman/Lahman.pdf) package in R is a great resource for historical statistics. There are 24 data sets with team, individual, manager, all-star, and hall-of-fame information in them. For more info, see this [link](http://lahman.r-forge.r-project.org/). (**Rstats**)

- If you don't use R, you can access the raw data from Lahman's site [here](http://www.seanlahman.com/baseball-archive/statistics/).

- Carson's [PitchFX](http://cpsievert.github.io/pitchRx/) package contains location data for MLB pitches from roughly the past decade. (**Rstats**). There's also a more [technical](https://journal.r-project.org/archive/2014-1/sievert.pdf) primer. 

- Dan Brooks' [site](http://www.brooksbaseball.net/) also has valuable XY data, produced almost instantanously. 

- Bill Petti is working on a baseball package in R that is promising. See his github page [here](https://github.com/BillPetti/baseballr). The focus is on the more recent baseball methodology. (**Rstats**)

- Jim & Max's [BaseballwithR book](http://www.amazon.com/Analyzing-Baseball-Data-Chapman-Series/dp/1466570229) and [webpage](https://baseballwithr.wordpress.com) provide lots of walkthroughs of historically important baseball examples. (**Rstats**)

- [Retrosheet](http://www.retrosheet.org/) has box-scores dating back to the 1800's, although I don't have any experience getting this information into R. 

- Darren at [Baseball Savant](www.baseballsavant) has some great pitch-level, searchable data. I used it for my umpire piece [here](http://fivethirtyeight.com/features/umpires-are-less-blind-than-they-used-to-be/), and found the ump-level search information quite interesting.

- Ben, Greg, and Shane wrote a statistical paper on [wins above replacement](http://arxiv.org/abs/1312.7158) (called openWAR), and their R [package](https://github.com/beanumber/openWAR) and [tutorial](https://baseballwithr.wordpress.com/2014/03/17/introduction-to-openwar/) are worth a read, particularly among those ready for more advanced analyses. Jim Albert's [tutorials](https://baseballwithr.wordpress.com/category/openwar/) will help you along. (**Rstats**)


### Football

- [Armchair Analysis](www.armchairanalysis.com) has parsed play-by-play data for all NFL games since 2000, split among roughly 15 data sets. I highly recommend, but there's a subscription required (yearly or seasonally).

- Brian Burke's old [site](http://archive.advancedfootballanalytics.com/2010/04/play-by-play-data.html) has unparsed play-by-play data for several seasons. It's free, but may take a bit of cleaning.

- Football Outsiders' advanced metrics may be worth a [look](http://www.footballoutsiders.com/). 

- Darren at [NFL Savant](http://nflsavant.com/about.php) has the last three seasons (2013 - 2015) ready for download. There's also a .csv with the results of the NFL's combine from 1999-2015. 

- I've used Sunshine's [data](http://www.repole.com/sun4cast/data.html) to get spread information for NFL and NCAA games. 

- For those more comfortable with Python, Ben [scrapes](https://github.com/burntSushi/nfldb) game, player, and play information for games since 2009.


### Basketball

I'm looking for a public data set will shot-level information across several years. In the meantime, what's provided is mostly walk-through's of how one can scrape game, team, and player-level data. 

- [The Data Game](http://thedatagame.com.au/2015/09/27/how-to-create-nba-shot-charts-in-r/) provides a tutorial on making a shot chart using R and ggplot. (**Rstats**)

- [Alex Bresler](http://asbcllc.com/blog/2014/november/creating_bref_scraper/) provides an entertaining walk-through of using R to scrape basketball reference. (**RStats**)

- [Nathan Yao](https://flowingdata.com/2010/01/21/how-to-make-a-heatmap-a-quick-and-easy-solution/)'s heatmap of NBA player stats is easy to implement. (**RStats**)

- Darren at [NBA Savant](http://nbasavant.com/shot_search.php) has a shot search tool, as well as the data from the NBA's two-minute report, which show [questionable calls](nbasavant.com/apps/twoMinuteReport.php) in the final minutes of close games. 

- Jun's [Github page](https://github.com/JunWorks/NBAstat/blob/master/shot.csv) includes a link to all 2014-15 NBA shots, with some shot-level data. It's not perfect, but it's a promising resource. (**Rstats**)

- There are lots of shot-charts out there: I liked this one from [Todd](http://toddwschneider.com/posts/ballr-interactive-nba-shot-charts-with-r-and-shiny/), as its reproducible and traces back several years. (**Rstats**)

- [Alex](https://github.com/abresler/nbastatR) wrote an R package that links to several different basketball sites, while [Ryan](https://github.com/rtelmore/ballr) also has one in the works which can scrape standings and stats directly. (**Rstats**)

- For those more comfortable with Python, Daniel [scrapes](http://danielfrg.com/blog/2013/04/01/nba-scraping-data/) games and player stats, and Greg [digs into](http://www.gregreda.com/2015/02/15/web-scraping-finding-the-api/) the league's API


